project_id = "vzrnxiowtshzspybrxeq"

[functions.employee_keys]
verify_jwt = false

[functions.llm-proxy]
verify_jwt = false

[functions.elevenlabs-conversation-token]
verify_jwt = false

[functions.sync-models]
verify_jwt = false
